# Dados

O projeto tem um conjunto de dados fornecido pelo Kaggle chamado nba.csv. NA base apresenta os dados dos jogadores de todas as temporadas de 1951 a 2022, com um total de 33330 ocorrências

## Descrição da base

As colunas são descritas a seguir:

POR JOGADOR:

| Variável           | Descrição                                                                                                                                                                                        |
|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Rank               | A classificação do jogador (ordenado por pontos marcados a cada temporada)                                                                                                                       |
| Year               | O ano da temporada (por exemplo, "2018-19")                                                                                                                                                      |
| Season Start Year  | O ano de início da temporada (por exemplo, 2018)                                                                                                                                                 |
| Season Type        | Temporada regular ou playoffs                                                                                                                                                                    |
| Player ID          | Um ID gerado para cada jogador                                                                                                                                                                   |
| Player             | O nome do jogador                                                                                                                                                                                |
| Team ID            | ID gerado para cada equipe                                                                                                                                                                       |
| Team               | A equipe do jogador na respectiva temporada                                                                                                                                                      |
| Games Played       | Jogos disputados na respectiva temporada                                                                                                                                                         |
| Minutes Played     | Minutos jogados na respectiva temporada                                                                                                                                                          |
| FG Made            | Cestas de campo convertidas (Field Goals Made)                                                                                                                                                   |
| FG Attempts        | Tentativas de cestas de campo (Field Goals Attempted)                                                                                                                                            |
| FG %               | Porcentagem de acertos de cestas de campo (Field Goal Percentage)                                                                                                                                |
| 3-Pt FG Made       | Cestas de três pontos convertidas (3 Point Field Goals Made)                                                                                                                                     |
| 3-Pt FG Attempts   | Tentativas de cestas de três pontos (3 Point Field Goals Attempted)                                                                                                                              |
| 3-Pt FG %          | Porcentagem de acertos de cestas de três pontos (3 Point Field Goal Percentage)                                                                                                                  |
| FT Made            | Lances livres convertidos (Free Throws Made)                                                                                                                                                     |
| FT Attempts        | Tentativas de lances livres (Free Throws Attempted)                                                                                                                                              |
| FT %               | Porcentagem de acertos de lances livres (Free Throw Percentage)                                                                                                                                  |
| Offensive Rebounds | Rebotes ofensivos                                                                                                                                                                                |
| Defensive Rebounds | Rebotes defensivos                                                                                                                                                                               |
| Rebounds           | Total de rebotes (ofensivos + defensivos)                                                                                                                                                        |
| Assists            | Assistências                                                                                                                                                                                     |
| Steals             | Roubos de bola                                                                                                                                                                                   |
| Blocks             | Tocos (bloqueios de arremessos)                                                                                                                                                                  |
| Turnovers          | Perdas de bola (erros)                                                                                                                                                                           |
| Personal Fouls     | Faltas pessoais                                                                                                                                                                                  |
| Points Scored      | Pontos marcados                                                                                                                                                                                  |
| Efficiency         | Eficiência calculada como (Pontos Marcados + Rebotes + Assistências + Roubos de Bola + Tocos - Chutes de Campo Perdidos - Lances Livres Perdidos - Perdas de Bola) dividido por Jogos Disputados |
| AST/TOV            | Taxa de assistências para turnovers (Assist-to-Turnover ratio)                                                                                                                                   |
| STL/TOV            | Taxa de roubos de bola para turnovers (Steal-to-Turnover ratio)                                                                                                                                  |
